services:
  orchestrator:
    build: ./apps/orchestrator
    container_name: agent-orchestrator
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
      - TZ=${TZ:-Asia/Bangkok}
      - WEBROOT=/app/workspace/generated-app/apps/web
    volumes:
      - ./workspace/generated-app/apps/web:/app/workspace/generated-app/apps/web
    ports:
      - "9000:9000"
    command: uvicorn main:app --host 0.0.0.0 --port 9000 --proxy-headers --forwarded-allow-ips="*"

  web:
    image: nginx:1.27-alpine
    container_name: agent-web
    ports:
      - "8080:80"
    volumes:
      - ./apps/web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./apps/web:/usr/share/nginx/html:ro
      - ./workspace/generated-app/apps/web:/usr/share/nginx/html/app
    depends_on:
      - orchestrator
