version: '3.8'
services:
  user-service:
    build: ./services/user-service
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=mongodb
    depends_on:
      - mongodb

  product-service:
    build: ./services/product-service
    ports:
      - "3002:3000"
    depends_on:
      - mongodb

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:3000"
    depends_on:
      - user-service
      - product-service

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  mongodb_data:
