FROM python:3.11-slim

# ติดตั้ง dependencies พื้นฐาน
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# ตั้งค่า workdir
WORKDIR /app

# copy requirements.txt ถ้ามี
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# copy project ทั้งหมด
COPY . /app

# run FastAPI
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
